project_name: "contrastive_learning"
base_save_dir: "/ext/trey/experiment_diffusion/experiment_rfdiffusion/models"
epochs: 100
adam_betas:
  - 0.9
  - 0.999
gamma: 0.999999
ae_in_channels: 2
ae_channels: 16
ae_multipliers:
  - 1
  - 2
  - 4
ae_factors:
  - 2
  - 2
ae_num_blocks:
  - 4
  - 4
ae_patch_size: 1
ae_resnet_groups: 8
ae_bottleneck: 2
ae_sigma: 0.4
dataset_path: "/ext/trey/experiment_diffusion/experiment_rfdiffusion/dataset/GOLD_XYZ_OSC.0001_1024.hdf5"
dataset_name: "DeepSig2018Dataset"
num_workers: 8
save_every: 10
early_stopping_patience: 5
